### ISSUE TITLE
crash/doesn't start on imac g3

### ISSUE THREAD

**Issue by yumikonoua** [BlackBirdLC/Aquafox#1]
I don't know how to "debug" but the browser crash/doesn't start on my imac g3

**Comment by yumikonoua** [comment]
edit: I actually found the crash report, here is:
`**********

Host Name:      imac-di-yumiko-noua
Date/Time:      2024-07-25 20:14:56.400 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: aquafox
Path:    /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/aquafox
Parent:  WindowServer [60]

Version: 45.41.6 (4524.7.24)

PID:    213
Thread: Unknown

Link (dyld) error:

Library not loaded: /opt/macports-tff/lib/libgcc/libatomic.1.dylib
  Referenced from: /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/libmozglue.dylib
  Reason: image not found
**********

Host Name:      imac-di-yumiko-noua
Date/Time:      2024-07-25 20:14:59.009 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: aquafox
Path:    /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/aquafox
Parent:  WindowServer [60]

Version: 45.41.6 (4524.7.24)

PID:    215
Thread: Unknown

Link (dyld) error:

Library not loaded: /opt/macports-tff/lib/libgcc/libatomic.1.dylib
  Referenced from: /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/libmozglue.dylib
  Reason: image not found
**********

Host Name:      imac-di-yumiko-noua
Date/Time:      2024-07-25 20:15:01.242 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: aquafox
Path:    /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/aquafox
Parent:  WindowServer [60]

Version: 45.41.6 (4524.7.24)

PID:    217
Thread: Unknown

Link (dyld) error:

Library not loaded: /opt/macports-tff/lib/libgcc/libatomic.1.dylib
  Referenced from: /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/libmozglue.dylib
  Reason: image not found
**********

Host Name:      imac-di-yumiko-noua
Date/Time:      2024-07-25 20:16:12.214 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: aquafox
Path:    /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/aquafox
Parent:  WindowServer [60]

Version: 45.41.6 (4524.7.24)

PID:    224
Thread: Unknown

Link (dyld) error:

Library not loaded: /opt/macports-tff/lib/libgcc/libatomic.1.dylib
  Referenced from: /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/libmozglue.dylib
  Reason: image not found
**********

Host Name:      imac-di-yumiko-noua
Date/Time:      2024-07-25 20:16:13.807 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: aquafox
Path:    /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/aquafox
Parent:  WindowServer [60]

Version: 45.41.6 (4524.7.24)

PID:    226
Thread: Unknown

Link (dyld) error:

Library not loaded: /opt/macports-tff/lib/libgcc/libatomic.1.dylib
  Referenced from: /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/libmozglue.dylib
  Reason: image not found
**********

Host Name:      imac-di-yumiko-noua
Date/Time:      2024-07-25 20:17:47.245 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: aquafox
Path:    /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/aquafox
Parent:  WindowServer [60]

Version: 45.41.6 (4524.7.24)

PID:    229
Thread: Unknown

Link (dyld) error:

Library not loaded: /opt/macports-tff/lib/libgcc/libatomic.1.dylib
  Referenced from: /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/libmozglue.dylib
  Reason: image not found
**********

Host Name:      imac-di-yumiko-noua
Date/Time:      2024-07-25 20:17:48.985 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: aquafox
Path:    /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/aquafox
Parent:  WindowServer [60]

Version: 45.41.6 (4524.7.24)

PID:    231
Thread: Unknown

Link (dyld) error:

Library not loaded: /opt/macports-tff/lib/libgcc/libatomic.1.dylib
  Referenced from: /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/libmozglue.dylib
  Reason: image not found
**********

Host Name:      imac-di-yumiko-noua
Date/Time:      2024-07-25 20:18:01.648 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: aquafox
Path:    /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/aquafox
Parent:  WindowServer [60]

Version: 45.41.6 (4524.7.24)

PID:    233
Thread: Unknown

Link (dyld) error:

Library not loaded: /opt/macports-tff/lib/libgcc/libatomic.1.dylib
  Referenced from: /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/libmozglue.dylib
  Reason: image not found
**********

Host Name:      imac-di-yumiko-noua
Date/Time:      2024-07-25 20:19:56.326 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: aquafox
Path:    /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/aquafox
Parent:  WindowServer [60]

Version: 45.41.6 (4524.7.24)

PID:    236
Thread: Unknown

Link (dyld) error:

Library not loaded: /opt/macports-tff/lib/libgcc/libatomic.1.dylib
  Referenced from: /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/libmozglue.dylib
  Reason: image not found
**********

Host Name:      imac-di-yumiko-noua
Date/Time:      2024-07-25 20:20:27.473 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: aquafox
Path:    /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/aquafox
Parent:  WindowServer [60]

Version: 45.41.6 (4524.7.24)

PID:    239
Thread: Unknown

Link (dyld) error:

Library not loaded: /opt/macports-tff/lib/libgcc/libatomic.1.dylib
  Referenced from: /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/libmozglue.dylib
  Reason: image not found
**********

Host Name:      imac-di-yumiko-noua
Date/Time:      2024-07-25 20:20:31.158 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: aquafox
Path:    /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/aquafox
Parent:  WindowServer [60]

Version: 45.41.6 (4524.7.24)

PID:    241
Thread: Unknown

Link (dyld) error:

Library not loaded: /opt/macports-tff/lib/libgcc/libatomic.1.dylib
  Referenced from: /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/libmozglue.dylib
  Reason: image not found
**********

Host Name:      imac-di-yumiko-noua
Date/Time:      2024-07-25 20:20:33.262 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: aquafox
Path:    /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/aquafox
Parent:  WindowServer [60]

Version: 45.41.6 (4524.7.24)

PID:    243
Thread: Unknown

Link (dyld) error:

Library not loaded: /opt/macports-tff/lib/libgcc/libatomic.1.dylib
  Referenced from: /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/libmozglue.dylib
  Reason: image not found
**********

Host Name:      imac-di-yumiko-noua
Date/Time:      2024-07-25 20:20:35.098 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: aquafox
Path:    /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/aquafox
Parent:  WindowServer [60]

Version: 45.41.6 (4524.7.24)

PID:    245
Thread: Unknown

Link (dyld) error:

Library not loaded: /opt/macports-tff/lib/libgcc/libatomic.1.dylib
  Referenced from: /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/libmozglue.dylib
  Reason: image not found
**********

Host Name:      imac-di-yumiko-noua
Date/Time:      2024-07-25 20:20:36.713 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: aquafox
Path:    /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/aquafox
Parent:  WindowServer [60]

Version: 45.41.6 (4524.7.24)

PID:    247
Thread: Unknown

Link (dyld) error:

Library not loaded: /opt/macports-tff/lib/libgcc/libatomic.1.dylib
  Referenced from: /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/libmozglue.dylib
  Reason: image not found
**********

Host Name:      imac-di-yumiko-noua
Date/Time:      2024-07-25 20:20:40.285 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: aquafox
Path:    /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/aquafox
Parent:  WindowServer [60]

Version: 45.41.6 (4524.7.24)

PID:    249
Thread: Unknown

Link (dyld) error:

Library not loaded: /opt/macports-tff/lib/libgcc/libatomic.1.dylib
  Referenced from: /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/libmozglue.dylib
  Reason: image not found
**********

Host Name:      imac-di-yumiko-noua
Date/Time:      2024-07-25 20:20:41.939 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: aquafox
Path:    /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/aquafox
Parent:  WindowServer [60]

Version: 45.41.6 (4524.7.24)

PID:    251
Thread: Unknown

Link (dyld) error:

Library not loaded: /opt/macports-tff/lib/libgcc/libatomic.1.dylib
  Referenced from: /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/libmozglue.dylib
  Reason: image not found
**********

Host Name:      imac-di-yumiko-noua
Date/Time:      2024-07-25 20:25:59.336 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: aquafox
Path:    /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/aquafox
Parent:  WindowServer [60]

Version: 45.41.6 (4524.7.24)

PID:    256
Thread: Unknown

Link (dyld) error:

Library not loaded: /opt/macports-tff/lib/libgcc/libatomic.1.dylib
  Referenced from: /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/libmozglue.dylib
  Reason: image not found
**********

Host Name:      imac-di-yumiko-noua
Date/Time:      2024-07-25 20:34:03.699 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: aquafox
Path:    /Volumes/Aquafox-G3-1.0.0-beta1/Aquafox.app/Contents/MacOS/aquafox
Parent:  WindowServer [60]

Version: 45.41.6 (4524.7.24)

PID:    284
Thread: Unknown

Link (dyld) error:

Library not loaded: /opt/macports-tff/lib/libgcc/libatomic.1.dylib
  Referenced from: /Volumes/Aquafox-G3-1.0.0-beta1/Aquafox.app/Contents/MacOS/libmozglue.dylib
  Reason: image not found
**********

Host Name:      imac-di-yumiko-noua
Date/Time:      2024-07-25 20:37:17.516 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: aquafox
Path:    /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/aquafox
Parent:  WindowServer [60]

Version: 45.41.6 (4524.7.24)

PID:    291
Thread: Unknown

Link (dyld) error:

Library not loaded: /opt/macports-tff/lib/libgcc/libatomic.1.dylib
  Referenced from: /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/libmozglue.dylib
  Reason: image not found

`

**Comment by BlackBirdLC** [comment]
Hi! Thank you for your report. The G3 build launches on a G5, I haven't gotten around to testing it on a G3 yet, I will probably do that tomorrow. In the meantime, could you test if the "attached" build works on your iMac?

https://thewireless.nekoweb.org/Aquafox-G3-1.0.0-beta1-yumikonoua.zip

**Comment by yumikonoua** [comment]
> Hi! Thank you for your report. The G3 build launches on a G5, I haven't gotten around to testing it on a G3 yet, I will probably do that tomorrow. In the meantime, could you test if the "attached" build works on your iMac?
> 
> https://thewireless.nekoweb.org/Aquafox-G3-1.0.0-beta1-yumikonoua.zip

hi! I test the attached build and Aquafox crash with the same error..

`Host Name:      imac-di-yumiko-noua
Date/Time:      2024-07-25 20:14:56.400 +0200
OS Version:     10.4.11 (Build 8S165)
Report Version: 4

Command: aquafox
Path:    /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/aquafox
Parent:  WindowServer [60]

Version: 45.41.6 (4524.7.24)

PID:    213
Thread: Unknown

Link (dyld) error:

Library not loaded: /opt/macports-tff/lib/libgcc/libatomic.1.dylib
  Referenced from: /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/libmozglue.dylib
  Reason: image not found`

**Comment by yumikonoua** [comment]
> > Hi! Thank you for your report. The G3 build launches on a G5, I haven't gotten around to testing it on a G3 yet, I will probably do that tomorrow. In the meantime, could you test if the "attached" build works on your iMac?
> > https://thewireless.nekoweb.org/Aquafox-G3-1.0.0-beta1-yumikonoua.zip
> 
> hi! I have tested the attached build and Aquafox crash with the same error..
> 
> `Host Name: imac-di-yumiko-noua Date/Time: 2024-07-25 20:14:56.400 +0200 OS Version: 10.4.11 (Build 8S165) Report Version: 4
> 
> Command: aquafox Path: /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/aquafox Parent: WindowServer [60]
> 
> Version: 45.41.6 (4524.7.24)
> 
> PID: 213 Thread: Unknown
> 
> Link (dyld) error:
> 
> Library not loaded: /opt/macports-tff/lib/libgcc/libatomic.1.dylib Referenced from: /Users/yumikonoua/Desktop/Aquafox.app/Contents/MacOS/libmozglue.dylib Reason: image not found`

update: after installing the [The Unofficial TenFourFox Tool-Kit](https://macintoshgarden.org/apps/the-unofficial-tenfourfox-toolkit) now the browser start fine, maybe you need to put that library (libatomic.1.dylib) in the browser sources? I don't know.
![Immagine_1](https://github.com/user-attachments/assets/a7dbb90e-3bdf-4ae5-9e2f-d9c9229fcf12)

**Comment by BlackBirdLC** [comment]
I'm having a hard time getting Tiger to boot on my G3 because of the IDE-to-SATA adapter and the SSD I'm using. So, I can't test anything on the G3 until I fix it. I've put a note on the release page with your workaround.

**Comment by yumikonoua** [comment]
> I'm having a hard time getting Tiger to boot on my G3 because of the IDE-to-SATA adapter and the SSD I'm using. So, I can't test anything on the G3 until I fix it. I've put a note on the release page with your workaround.

👍 (r.i.p. g3)

**Comment by BlackBirdLC** [comment]
None of the builds would launch on a G5 without MacPorts, so I removed them from the releases. I reverted to an older version of the build script and managed to compile a G3 version with all the necessary libraries included. I'm pretty sure this build will work on a G3. I've uploaded it to releases, and builds for G4 and G5 are on the way. Could you confirm if the new build fixes the problem so I can close the issue? 

You can downloaded it from this [direct link](https://github.com/BlackBirdLC/Aquafox/releases/download/v1.0.0-beta1/Aquafox-G3-1.0.0-beta1.dmg) or from the releases page.

**Comment by yumikonoua** [comment]
> None of the builds would launch on a G5 without MacPorts, so I removed them from the releases. I reverted to an older version of the build script and managed to compile a G3 version with all the necessary libraries included. I'm pretty sure this build will work on a G3. I've uploaded it to releases, and builds for G4 and G5 are on the way. Could you confirm if the new build fixes the problem so I can close the issue?
> 
> You can downloaded it from this [direct link](https://github.com/BlackBirdLC/Aquafox/releases/download/v1.0.0-beta1/Aquafox-G3-1.0.0-beta1.dmg) or from the releases page.

I can confirm now works fine, thanks!

**Comment by HinataNekoNya** [comment]
Sa plante aussi sur g4 je me permet d'écrire ici car je pense que c'est peut-être lier mais j'en suis pas sur chez moi il se ferme et je sais pas trop ou trouver les logs mais en tout cas j'ai les mêmes symptômes.

**Comment by HinataNekoNya** [comment]
Si jamais tu tien a ma faire essayer un truc je tien a dire que j'ai la version G4-7450

**Comment by HinataNekoNya** [comment]
Après vérification mon problème est peut être tout autre. Mon g4 est sous Panther et je n'arrive pas a le mettre a jours vers Tigers.
